#!/bin/bash

echo "🚀 QR Restaurant Menu App - Production Deployment"
echo "=================================================="

echo ""
echo "📋 Prerequisites Check:"
echo "1. GitHub repository: vcmnamban/QR-Restaurant-Menu-App ✅"
echo "2. Railway account: [railway.app](https://railway.app)"
echo "3. Vercel account: [vercel.com](https://vercel.com)"
echo "4. MongoDB Atlas account (optional): [mongodb.com/atlas](https://mongodb.com/atlas)"

echo ""
echo "🌐 Step 1: Deploy Backend to Railway"
echo "-------------------------------------"
echo "1. Go to [railway.app](https://railway.app)"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New Project'"
echo "4. Select 'Deploy from GitHub repo'"
echo "5. Choose: vcmnamban/QR-Restaurant-Menu-App"
echo "6. Root Directory: backend"
echo "7. Build Command: npm install"
echo "8. Start Command: npm run build && npm start"
echo "9. Add environment variables from: backend/railway.env.example"
echo "10. Click 'Deploy'"

echo ""
echo "🎨 Step 2: Deploy Frontend to Vercel"
echo "-------------------------------------"
echo "1. Go to [vercel.com](https://vercel.com)"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New Project'"
echo "4. Import: vcmnamban/QR-Restaurant-Menu-App"
echo "5. Root Directory: frontend"
echo "6. Framework Preset: Vite"
echo "7. Build Command: npm run build"
echo "8. Output Directory: dist"
echo "9. Add VITE_API_URL with your Railway backend URL"
echo "10. Click 'Deploy'"

echo ""
echo "🔗 Step 3: Connect Frontend to Backend"
echo "---------------------------------------"
echo "1. Update VITE_API_URL in Vercel with Railway backend URL"
echo "2. Redeploy if necessary"
echo "3. Test the connection"

echo ""
echo "✅ Deployment Checklist:"
echo "- [ ] Backend deployed to Railway"
echo "- [ ] Frontend deployed to Vercel"
echo "- [ ] Environment variables configured"
echo "- [ ] Frontend connecting to backend"
echo "- [ ] All features functional"

echo ""
echo "🌟 After Deployment:"
echo "Frontend: https://your-project.vercel.app"
echo "Backend: https://your-project.railway.app"
echo "Health Check: https://your-project.railway.app/health"

echo ""
echo "🎉 Ready to launch your restaurant empire! 🚀"
